import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { renderToStaticMarkup } from "react-dom/server";
import type { RankedProduct } from "../lib/app-shell.ts";
import { ResultsPage } from "./ResultsPage.tsx";

function makeProduct(overrides: Partial<RankedProduct>): RankedProduct {
  return {
    id: "p1",
    name: "Nebula Match",
    price: 269,
    score: 96,
    maxDb: 42,
    waterproof: 7,
    appearance: "high_disguise",
    physicalForm: "external",
    motorType: "gentle",
    gender: "female",
    brand: "Brand",
    brandBrief: {
      brandName: "Brand",
      brandSlug: "brand",
      countryLabel: "德国",
      positioning: "偏设计感与材质完成度的一线品牌。",
      styleSummary: "整体风格更现代、克制，也更强调稳定体验。",
    },
    material: "Silicone",
    imagePlaceholder: "",
    tags: ["静音"],
    matchSummary: ["适配当前使用方向", "价格落在预算区间内"],
    hardMisses: 0,
    budgetGap: 0,
    noiseGap: 0,
    ...overrides,
  };
}

test("female MVP result primary card renders as a social share card with practical checks", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["静音"],
        maxDb: 50,
        waterproof: 7,
        budget: [100, 300],
      }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          reason: "42dB 更贴近静音需求，防水表现达到 IPX7。",
        }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /female-mvp-result-share-card/);
  assert.match(html, /生成分享图/);
  assert.doesNotMatch(html, /\/assets\/results\/luna-result-sticker\.png/);
  assert.doesNotMatch(html, /\/assets\/results\/luna-result-decorations/);
  assert.doesNotMatch(html, /\/assets\/results\/luna-result-footer-flight/);
  assert.doesNotMatch(html, /\/assets\/results\/luna-result-sticker-badge/);
  assert.match(html, /\/assets\/results\/luna-result-guide\.png/);
  assert.match(html, /LUNA STAGE/);
  assert.match(html, /这一款可以先看/);
  assert.match(html, /female-mvp-result-share-card__stage/);
  assert.match(html, /female-mvp-result-share-card__luna-halo/);
  assert.doesNotMatch(html, /female-mvp-result-share-card__luna-signal/);
  assert.match(html, /female-mvp-result-share-card__ask/);
  assert.match(html, /female-mvp-result-share-card__ask-status/);
  assert.match(html, /\/assets\/results\/luna-result-sticker-check\.png/);
  assert.match(html, /\/assets\/results\/luna-result-sticker-share-seal\.png/);
  assert.match(html, /为什么先推荐这一款？/);
  assert.match(html, /声音够安静吗？/);
  assert.match(html, /买前要确认什么？/);
  assert.doesNotMatch(html, /LUNA GUIDE/);
  assert.match(html, /female-mvp-result-share-card__product-info/);
  assert.match(html, /关键判断/);
  assert.doesNotMatch(html, /LUNA MATCH CARD/);
  assert.doesNotMatch(html, /我的本轮适配装备/);
  assert.doesNotMatch(html, /按使用场景、声音、清洁和上手难度生成/);
  assert.doesNotMatch(html, /FIT SNAPSHOT/);
  assert.doesNotMatch(html, /适合先这样判断/);
  assert.match(html, /声音/);
  assert.match(html, /清洁/);
  assert.match(html, /外部路线更适合先找身体反馈/);
  assert.doesNotMatch(html, /下单前确认/);
  assert.match(html, /Generated by Luna/);
  assert.match(html, /生成分享图/);
  assert.match(html, /42dB 更贴近静音需求/);
  assert.match(html, /IPX7/);
  assert.doesNotMatch(html, /声音：42dB[\s\S]*清洁：IPX7[\s\S]*上手：/);
  assert.doesNotMatch(html, /为什么适合/);
  assert.doesNotMatch(html, /需要留意/);
});

test("female MVP share image opens a separate editor modal before downloading", () => {
  const source = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  assert.match(source, /setIsShareEditorOpen\(true\)/);
  assert.match(source, /female-mvp-share-editor__modal/);
  assert.match(source, /female-mvp-share-editor__canvas/);
  assert.match(source, /下载分享图/);
  assert.match(source, /luna-result-sticker\.png/);
  assert.doesNotMatch(source, /src: "\/assets\/results\/luna-result-decorations\.png"/);
  assert.match(source, /luna-result-decoration-stars\.png/);
  assert.match(source, /luna-result-decoration-planet\.png/);
  assert.match(source, /luna-result-decoration-orbit\.png/);
  assert.match(source, /luna-result-decoration-hearts\.png/);
  assert.match(source, /luna-result-decoration-cloud\.png/);
  assert.match(source, /luna-result-decoration-sparkles\.png/);
  assert.match(source, /luna-result-footer-flight\.png/);
  assert.match(source, /luna-result-sticker-badge\.png/);
  assert.match(source, /luna-result-sticker-arrow\.png/);
  assert.match(source, /luna-result-sticker-shield\.png/);
  assert.match(source, /luna-result-sticker-magnifier\.png/);
  assert.match(source, /luna-result-sticker-orbit-ring\.png/);
  assert.match(source, /onPointerDown/);
  assert.match(source, /onPointerMove/);
  assert.match(source, /handleResetShareStickers/);
  assert.match(source, /DEFAULT_SHARE_STICKER_ASSET_IDS/);
  assert.doesNotMatch(
    source,
    /DEFAULT_SHARE_STICKER_ASSET_IDS[\s\S]*luna-result-decoration-sparkles/,
  );
  assert.doesNotMatch(
    source,
    /DEFAULT_SHARE_STICKER_ASSET_IDS[\s\S]*luna-result-sticker-arrow/,
  );
  assert.doesNotMatch(
    source,
    /DEFAULT_SHARE_STICKER_ASSET_IDS[\s\S]*luna-result-sticker-shield/,
  );
  assert.doesNotMatch(
    source,
    /DEFAULT_SHARE_STICKER_ASSET_IDS[\s\S]*luna-result-sticker-magnifier/,
  );
  assert.doesNotMatch(
    source,
    /DEFAULT_SHARE_STICKER_ASSET_IDS[\s\S]*luna-result-sticker-orbit-ring/,
  );
  assert.match(source, /createDefaultShareStickers/);
  assert.match(source, /handleClearShareStickers/);
  assert.match(source, /清空贴纸/);
  assert.match(source, /恢复初始/);
  assert.match(source, /handleDeleteSelectedShareSticker/);
  assert.match(source, /female-mvp-share-editor__canvas--exporting/);
  assert.match(source, /setSelectedShareStickerId\(null\)/);
  assert.match(source, /luna-result-edited-share\.png/);
});

test("female MVP results hide heavy secondary modules", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["女性向", "新手友好"] }}
      topProducts={[
        makeProduct({
          id: "female-good",
          gender: "female",
          reason: "适合女性向新手外部探索。",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /female-mvp-results/);
  assert.match(html, /min-h-\[100svh\]/);
  assert.match(html, /LUNA RESULT/);
  assert.match(html, /这一款可以先看/);
  assert.doesNotMatch(html, /先看主推荐和关键理由/);
  assert.doesNotMatch(html, /基于你的刺激路径/);
  assert.doesNotMatch(html, /身体人格/);
  assert.doesNotMatch(html, /知识星云/);
  assert.doesNotMatch(html, /去知识星云/);
  assert.doesNotMatch(html, /完整星系人格/);
  assert.doesNotMatch(html, /快速微调结果/);
  assert.doesNotMatch(html, /主推荐横向对比/);
  assert.doesNotMatch(html, /购买前最终自检/);
  assert.doesNotMatch(html, /登录后可加密保存/);
  assert.doesNotMatch(html, /对当前结果不满意/);
});

test("female MVP result tags can expand from the hidden count chip", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["女性向", "外部震动", "平衡进阶", "静音", "温度限制"],
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );
  const source = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  assert.match(html, /aria-label="展开剩余 2 个匹配标签"/);
  assert.match(source, /areResultTagsExpanded \? resultTags : resultTags\.slice\(0, 3\)/);
  assert.match(source, /setAreResultTagsExpanded\(true\)/);
  assert.match(source, /setAreResultTagsExpanded\(false\)/);
  assert.match(source, /收起/);
});

test("female MVP results claim the full mobile canvas instead of sitting inside a dark shell", () => {
  const appSource = fs.readFileSync(path.resolve(process.cwd(), "src/App.tsx"), "utf8");
  const cssSource = fs.readFileSync(path.resolve(process.cwd(), "src/index.css"), "utf8");
  const resultsPageSource = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  assert.match(appSource, /const isFemaleMvpResultsRoute = effectiveShellRoute === "\/results" && isFemaleMvp;/);
  assert.match(appSource, /isFemaleMvpResultsRoute[\s\S]*\? "max-w-none"/);
  assert.match(appSource, /isFemaleMvpResultsRoute[\s\S]*\? "min-h-screen p-0"/);
  assert.match(appSource, /!isFemaleMvpResultsRoute/);
  assert.match(appSource, /isFemaleMvpResultsRoute \? "female-mvp-results-route" : ""/);
  assert.match(cssSource, /\.female-mvp-results-route \{[\s\S]*linear-gradient\(165deg, #fff8ea 0%, #ffe9f1 46%, #dff3ff 100%\);/);
  assert.doesNotMatch(resultsPageSource, /bg-black/);
  assert.doesNotMatch(resultsPageSource, /text-slate-200 transition-colors hover:border-cyan-300\/24 hover:bg-cyan-300/);
});

test("female MVP shows a lightweight brand brief with an official website link", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          brand: "We-Vibe",
          brandBrief: null,
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /female-mvp-result-share-card__brand-brief/);
  assert.match(html, /BRAND NOTE/);
  assert.match(html, /We-Vibe/);
  assert.match(html, /高端情趣科技品牌/);
  assert.match(html, /href="https:\/\/www.we-vibe.com\/"/);
  assert.match(html, /品牌官网/);
  assert.doesNotMatch(html, /去知识星云/);
  assert.match(html, /关键判断/);
});

test("results page shows the original natural language request when matched from free text", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "女性向"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
      matchInputMode="natural-language"
      naturalLanguageQuery="想要一个更静音、预算 300 以内、适合女生新手、最好容易清洁的产品。"
    />,
  );

  assert.match(html, /你的原始描述/);
  assert.match(html, /想要一个更静音、预算 300 以内、适合女生新手、最好容易清洁的产品。/);
  assert.match(html, /关键判断/);
  assert.doesNotMatch(html, /下单前确认/);
  assert.doesNotMatch(html, /你这次最该先确认/);
});

test("female MVP hides the body persona entry and free summary block", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /身体人格测试/);
  assert.doesNotMatch(html, /解锁你的身体人格画像/);
  assert.doesNotMatch(html, /星幕型·隐秘安全感者/);
  assert.doesNotMatch(html, /完整星系人格档案已锁定/);
  assert.doesNotMatch(html, /登录后可解锁完整星系人格档案/);
  assert.doesNotMatch(html, /0\.5 元一次解锁，可随时回看/);
  assert.match(html, /female-mvp-results/);
});

test("female MVP hides the body persona reopen entry even when the report is unlocked", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /完整星系人格档案已解锁/);
  assert.doesNotMatch(html, /再次查看完整档案/);
  assert.match(html, /female-mvp-results/);
});

test("results page shows a lightweight status while AI enhancement is still running", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[{
        ...makeProduct({ id: "b1", name: "Backup Pick" }),
        backupLabel: "更静音",
        backupReason: "本地备选说明先展示",
      }]}
      shoppingGuidance={["先用本地建议兜底"]}
      recommendationTips={[]}
      isEnhancingResults
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /AI 正在润色备选说明和选购建议/);
  assert.match(html, /主推荐已可先查看/);
  assert.match(html, /本地备选说明先展示/);
});

test("results page gives the core result shell roomier horizontal and panel padding", () => {
  const source = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  assert.match(
    source,
    /results-report-shell female-mvp-results relative isolate min-h-\[100svh\] w-full space-y-6 overflow-x-hidden px-4 pt-\[calc\(1\.25rem\+env\(safe-area-inset-top\)\)\]/,
  );
  assert.match(
    source,
    /results-report-panel relative z-10 overflow-hidden rounded-\[1\.75rem\] border border-cyan-200\/14 bg-slate-950\/56 p-5 shadow-\[0_24px_90px_rgba\(8,47,73,0\.2\)\] sm:p-6/,
  );
});

test("results page exposes a detail link for the primary recommendation when a product url is available", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          sourceUrl: "https://example.com/primary-pick",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /href="https:\/\/example.com\/primary-pick"/);
  assert.match(html, /点击查看详情/);
  assert.match(html, /female-mvp-result-share-card__detail-link/);
});

test("female MVP detail link uses a darker text color on the light pill", () => {
  const css = fs.readFileSync(
    path.resolve(process.cwd(), "src/index.css"),
    "utf8",
  );

  assert.match(
    css,
    /\.female-mvp-result-share-card__detail-link > span \{[\s\S]*color: #0c4a6e;/,
  );
  assert.match(
    css,
    /\.female-mvp-results \.text-cyan-100\\\/85 \{[\s\S]*color: #0c4a6e !important;/,
  );
  assert.match(
    css,
    /\.female-mvp-result-share-card__detail-link > span > span \{[\s\S]*color: #0c4a6e;/,
  );
  assert.match(
    css,
    /\.female-mvp-result-share-card__detail-link svg \{[\s\S]*background: linear-gradient\(135deg, #7dd3fc, #c4b5fd\);/,
  );
  assert.match(
    css,
    /\.female-mvp-result-share-card__detail-link svg \{[\s\S]*box-shadow: 0 0\.28rem 0\.7rem rgba\(14, 165, 233, 0\.14\);/,
  );
});

test("female MVP Luna stage removes the old framed portrait and uses GSAP stage motion", () => {
  const css = fs.readFileSync(
    path.resolve(process.cwd(), "src/index.css"),
    "utf8",
  );
  const panelSource = fs.readFileSync(
    path.resolve(
      process.cwd(),
      "src/components/results/ResultsPrimaryRecommendationPanel.tsx",
    ),
    "utf8",
  );
  const animationSource = fs.readFileSync(
    path.resolve(process.cwd(), "src/hooks/useResultsPageAnimation.ts"),
    "utf8",
  );
  const resultsPageSource = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  const lunaRule = css.match(
    /\.female-mvp-result-share-card__luna \{(?<body>[\s\S]*?)\n\}/,
  )?.groups?.body ?? "";
  const lunaStageOrbitRule = css.match(
    /\.female-mvp-result-share-card__stage-scene \.female-mvp-result-share-card__luna-orbit \{(?<body>[\s\S]*?)\n\}/,
  )?.groups?.body ?? "";
  const lunaFlightCloneRule = css.match(
    /\.female-mvp-result-share-card__luna-flight-clone \{(?<body>[\s\S]*?)\n\}/,
  )?.groups?.body ?? "";

  assert.doesNotMatch(lunaRule, /border:/);
  assert.doesNotMatch(lunaRule, /background:/);
  assert.match(lunaRule, /filter: drop-shadow/);
  assert.match(lunaStageOrbitRule, /top: -0\.25rem;/);
  assert.match(panelSource, /useLunaResultStageAnimation\(gsapMotionState\)/);
  assert.match(panelSource, /ref=\{lunaStageRef\}/);
  assert.doesNotMatch(panelSource, /female-mvp-result-share-card__luna-signal/);
  assert.match(animationSource, /export function useLunaResultStageAnimation/);
  assert.match(animationSource, /document\.createElement\("canvas"\)/);
  assert.match(animationSource, /drawImage\(lunaImage/);
  assert.match(animationSource, /lunaImage\.naturalWidth \/ lunaImage\.naturalHeight/);
  assert.match(animationSource, /drawWidth/);
  assert.match(animationSource, /drawHeight/);
  assert.match(animationSource, /drawX/);
  assert.match(animationSource, /drawY/);
  assert.doesNotMatch(
    animationSource,
    /drawImage\(lunaImage, 0, 0, finalRect\.width, finalRect\.height\)/,
  );
  assert.match(animationSource, /Math\.min\(window\.devicePixelRatio \|\| 1, 2\)/);
  assert.match(animationSource, /LUNA_FLIGHT_ACTIVE_CLASS/);
  assert.match(animationSource, /LUNA_FLIGHT_DELAY_SECONDS = 1\.5/);
  assert.match(animationSource, /lunaFlightStart = getGsapDuration\(LUNA_FLIGHT_DELAY_SECONDS, gsapMotionState\)/);
  assert.match(animationSource, /classList\.add\(LUNA_FLIGHT_ACTIVE_CLASS\)/);
  assert.match(animationSource, /classList\.remove\(LUNA_FLIGHT_ACTIVE_CLASS\)/);
  assert.match(animationSource, /flightClone\.style\.visibility = "hidden"/);
  assert.match(animationSource, /lunaArcPath/);
  assert.match(animationSource, /motionPath/);
  assert.match(animationSource, /curviness: 1\.25/);
  assert.match(animationSource, /autoRound: false/);
  assert.match(animationSource, /force3D: true/);
  assert.match(animationSource, /duration: getGsapDuration\(1\.38, gsapMotionState\)/);
  assert.match(animationSource, /createLunaFlightClone/);
  assert.match(animationSource, /document\.body\.appendChild\(flightClone\)/);
  assert.match(animationSource, /female-mvp-result-share-card__luna-flight-clone/);
  assert.match(animationSource, /window\.innerWidth \* 0\.08/);
  assert.match(animationSource, /window\.innerHeight \* 0\.07/);
  assert.match(animationSource, /visibility: "visible"/);
  assert.doesNotMatch(
    animationSource,
    /lunaFigure,[\s\S]{0,220}autoAlpha/,
  );
  assert.match(animationSource, /gsap\.quickTo/);
  assert.match(animationSource, /mapRange/);
  assert.match(css, /width: min\(54%, 12\.8rem\);/);
  assert.match(css, /width: min\(54%, 10\.6rem\);/);
  assert.match(css, /\.female-mvp-result-share-card__luna-flight-clone \{/);
  assert.match(css, /position: fixed;/);
  assert.match(lunaFlightCloneRule, /contain: layout paint style;/);
  assert.doesNotMatch(lunaFlightCloneRule, /filter:/);
  assert.match(css, /\.female-mvp-result-share-card__stage-scene--luna-flight::before/);
  assert.match(css, /animation-play-state: paused;/);
  assert.doesNotMatch(css, /female-mvp-result-luna-signal/);
  assert.match(resultsPageSource, /gsapMotionState=\{gsapMotionState\}/);
});

test("results page entrance animation does not replay on parent-only rerenders", () => {
  const animationSource = fs.readFileSync(
    path.resolve(process.cwd(), "src/hooks/useResultsPageAnimation.ts"),
    "utf8",
  );

  const resultsAnimationHookSource = animationSource.slice(
    animationSource.indexOf("export function useResultsPageAnimation"),
    animationSource.indexOf("export function useLunaResultStageAnimation"),
  );

  assert.doesNotMatch(resultsAnimationHookSource, /\}, \[gsapMotionState\]\);/);
  assert.match(
    resultsAnimationHookSource,
    /\}, \[gsapMotionState\.shouldAnimate, gsapMotionState\.prefersReducedMotion\]\);/,
  );
});

test("female MVP shows the primary recommendation brand above the product name outside the image", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          brand: "We-Vibe",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /本轮最贴合/);
  assert.match(html, /female-mvp-result-share-card__product-info/);
  assert.match(
    html,
    /female-mvp-result-share-card__product-info"><span>本轮最贴合<\/span><p>We-Vibe<\/p><div[^>]*><h3>Primary Pick<\/h3>/,
  );
  assert.match(
    html,
    /<p>We-Vibe<\/p><div[^>]*><h3>Primary Pick<\/h3>/,
  );
});

test("female MVP keeps the primary image area separate from the detail link hotspot", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          sourceUrl: "https://example.com/primary-pick",
          imagePlaceholder: "",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /Primary Pick 默认图片/);
  assert.match(html, /href="https:\/\/example.com\/primary-pick"/);
  assert.doesNotMatch(
    html,
    /<a[^>]*href="https:\/\/example\.com\/primary-pick"[\s\S]*Primary Pick 默认图片[\s\S]*Primary Pick[\s\S]*<\/a>/,
  );
});

test("female MVP keeps product copy out of the primary image area", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          brand: "We-Vibe",
          sourceUrl: "https://example.com/primary-pick",
          imagePlaceholder: "",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /female-mvp-result-share-card__product-info/);
  assert.match(html, /<p>We-Vibe<\/p>/);
  assert.match(html, /<h3>Primary Pick<\/h3>/);
  assert.match(html, /href="https:\/\/example.com\/primary-pick"/);
  assert.doesNotMatch(
    html,
    /<a[^>]*href="https:\/\/example\.com\/primary-pick"[\s\S]*Primary Pick 默认图片[\s\S]*Primary Pick[\s\S]*<\/a>/,
  );
});

test("female MVP folds practical cautions into the primary check card", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["路线待判断", "敏感度待判断"],
        maxDb: 40,
        experienceLevel: "sensitive",
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /下单前确认/);
  assert.match(html, /偏好暂未确定/);
  assert.doesNotMatch(html, /暂时不建议优先看/);
});

test("female MVP hides archive actions from the result page", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /保存推荐档案/);
  assert.doesNotMatch(html, /登录后可加密保存到云端/);
  assert.doesNotMatch(html, /查看档案/);
});

test("female MVP hides archive actions even when the auth session is already active", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /已登录/);
  assert.doesNotMatch(html, /taptaq/);
  assert.doesNotMatch(html, /登录 \/ 注册/);
  assert.doesNotMatch(html, /退出登录/);
  assert.doesNotMatch(html, /登录后可加密保存/);
  assert.doesNotMatch(html, /保存推荐档案/);
});

test("female MVP prioritizes the primary recommendation and removes secondary controls", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "入门级", "高伪装", "预算友好", "防水"] }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
        makeProduct({ id: "p3", name: "Third Pick", score: 82 }),
      ]}
      backupProducts={[]}
      shoppingGuidance={["优先确认清洁便利性"]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /results-report-shell/);
  assert.match(html, /LUNA RESULT/);
  assert.match(html, /这一款可以先看/);
  assert.match(html, /本轮最贴合/);
  assert.doesNotMatch(html, /用户名/);
  assert.doesNotMatch(html, /登录后可加密保存/);
  assert.doesNotMatch(html, /快速微调结果/);
  assert.doesNotMatch(html, /主推荐横向对比/);
  assert.doesNotMatch(html, /身体人格测试/);
  assert.doesNotMatch(html, /算法最匹配（第 1 推荐）/);
});

test("female MVP removes comparison, alternatives, tuning, and regeneration from the result page", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "高伪装"], appearance: "high_disguise" }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
        makeProduct({ id: "p3", name: "Third Pick", score: 82 }),
      ]}
      backupProducts={[
        {
          ...makeProduct({ id: "b1", name: "Backup Pick", score: 80 }),
          backupLabel: "更静音",
          backupReason: "更适合低打扰场景。",
        },
      ]}
      shoppingGuidance={["购买前优先确认是否有明确售后和材质说明。"]}
      recommendationTips={["如果同住，先优先比较更安静的路线。"]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /身体人格测试/);
  assert.match(html, /Primary Pick/);
  assert.doesNotMatch(html, /快速微调结果/);
  assert.doesNotMatch(html, /主推荐横向对比/);
  assert.doesNotMatch(html, /对当前结果不满意/);
  assert.doesNotMatch(html, /购买前最终自检/);
  assert.doesNotMatch(html, /登录后可加密保存/);
  assert.doesNotMatch(html, /Backup Pick/);
});

test("results page shows relaxation tips when strict matching finds no products", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["高伪装", "≥ IPX7 防水"],
        appearance: "high_disguise",
        waterproof: 7,
      }}
      topProducts={[]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[
        "如果可接受 IPX6 或基础防水，能解锁更多仍然好清洁的选择。",
      ]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /当前没有完全符合条件的玩具/);
  assert.match(html, /可以尝试放宽/);
  assert.match(html, /IPX6 或基础防水/);
});

test("female MVP hides the same-category library bridge after recommendation", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"], gender: "female" }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick", typeCode: "external_vibe" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /想自己再横向比一比？/);
  assert.doesNotMatch(html, /去装备库继续看同类路线、价位区间和不同品牌差异/);
  assert.doesNotMatch(html, /查看同类装备/);
});

test("female MVP hides comparison and backup headings", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
        makeProduct({ id: "p3", name: "Third Pick", score: 82 }),
      ]}
      backupProducts={[
        {
          ...makeProduct({ id: "b1", name: "Backup Pick", score: 80 }),
          backupLabel: "更静音",
          backupReason: "更适合低打扰场景。",
        },
      ]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /主推荐横向对比/);
  assert.doesNotMatch(html, /换个侧重点看看/);
  assert.doesNotMatch(html, /Top 3 快速对比/);
  assert.doesNotMatch(html, /Backup Pick/);
});

test("female MVP hides formal candidate groups, adjustment actions, and final checks", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "高伪装"], appearance: "high_disguise" }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
        makeProduct({ id: "p3", name: "Third Pick", score: 82 }),
      ]}
      backupProducts={[
        {
          ...makeProduct({ id: "b1", name: "Backup Pick", score: 80 }),
          backupLabel: "更静音",
          backupReason: "更适合低打扰场景。",
        },
      ]}
      shoppingGuidance={[
        "购买前优先确认是否有明确售后和材质说明。",
        "收到后先完成基础清洁，再进入第一次使用。",
      ]}
      recommendationTips={["如果同住，先优先比较更安静的路线。"]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /身体人格测试/);
  assert.doesNotMatch(html, /购买前再确认这几件事/);
  assert.doesNotMatch(html, /购买前最终自检/);
  assert.doesNotMatch(html, /快速微调结果/);
  assert.doesNotMatch(html, /这 3 个参数，和你这次更相关/);
});

test("female MVP hides tuning feedback and tuning buttons", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "微调：更安静"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /已应用更安静一点/);
  assert.doesNotMatch(html, /已应用：更安静一点/);
  assert.doesNotMatch(html, /快速微调结果/);
});

test("results page does not disable tuning buttons just because stale tuning tags exist in answers", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["静音", "微调：更安静", "微调：预算更低", "微调：新手友好"],
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /已应用更安静一点/);
  assert.doesNotMatch(html, /已应用预算低一点/);
  assert.doesNotMatch(html, /已应用更适合新手/);
  assert.doesNotMatch(
    html,
    /正在按所选方向重新计算推荐时，会保留当前问卷并更新结果。/,
  );
});

test("female MVP hides direct entry points to revise key quiz conditions", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "进阶级"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /想改一个条件？/);
  assert.doesNotMatch(html, /改预算/);
  assert.doesNotMatch(html, /改静音/);
  assert.doesNotMatch(html, /改场景/);
});

test("female MVP hides the stacked comparison view", () => {
  const source = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音", "进阶级", "预算友好"] }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88, price: 199 }),
        makeProduct({ id: "p3", name: "Third Pick", score: 84, price: 329 }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(source, /手机快速对比/);
  assert.doesNotMatch(source, /第 1 推荐/);
  assert.match(source, /Primary Pick/);
  assert.doesNotMatch(source, /Second Pick/);
  assert.doesNotMatch(source, /Third Pick/);
  assert.doesNotMatch(source, /min-w-\[44rem\]/);
});

test("female MVP hides archive mobile button layout", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /grid w-full grid-cols-1 gap-2 sm:flex sm:w-auto sm:flex-wrap/);
  assert.doesNotMatch(html, /保存推荐档案/);
});

test("results page no longer exposes a later-comparison candidate picker", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[
        makeProduct({ id: "p1", name: "Primary Pick" }),
        makeProduct({ id: "p2", name: "Second Pick", score: 88 }),
      ]}
      backupProducts={[
        {
          ...makeProduct({ id: "b1", name: "Budget Backup", score: 82 }),
          backupLabel: "更省预算",
          backupReason: "预算压力更小",
        },
      ]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /稍后比较/);
  assert.doesNotMatch(html, /已加入比较/);
  assert.doesNotMatch(html, /已选 1\/3/);
});

test("female MVP hides shopping guidance next-step sections", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[
        "购买前优先确认是否有明确售后和材质说明。",
        "收到后先完成基础清洁，再进入第一次使用。",
      ]}
      recommendationTips={["如果同住，先优先比较更安静的路线。"]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /购买前再确认这几件事/);
  assert.doesNotMatch(html, /购买前优先确认是否有明确售后和材质说明/);
  assert.doesNotMatch(html, /收到后先完成基础清洁/);
  assert.doesNotMatch(html, /结果提示/);
});

test("female MVP hides general shopping guidance next-step sections", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[
        "先比较主推和备选的静音差异。",
        "预算接近时，可优先看刺激方向差异。",
      ]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /选购时重点看/);
  assert.doesNotMatch(html, /先比较主推和备选的静音差异/);
  assert.doesNotMatch(html, /预算接近时，可优先看刺激方向差异/);
});

test("female MVP hides the final pre-purchase checklist", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["同住", "新手友好", "高伪装"],
        maxDb: 45,
        waterproof: 7,
        appearance: "high_disguise",
        experienceLevel: "sensitive",
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /购买前最终自检/);
  assert.doesNotMatch(html, /声音环境/);
  assert.doesNotMatch(html, /收纳隐私/);
  assert.doesNotMatch(html, /经验节奏/);
  assert.doesNotMatch(html, /下单前快速过一遍/);
  assert.doesNotMatch(html, /FINAL CHECK/);
});

test("female MVP hides route summary and keeps practical primary checks", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["同住", "新手友好", "高伪装"],
        maxDb: 45,
        waterproof: 7,
        appearance: "high_disguise",
        physicalForm: "external",
        experienceLevel: "sensitive",
      }}
      topProducts={[
        makeProduct({
          id: "p1",
          name: "Primary Pick",
          reason: "42dB 更贴近静音需求，外部路线也更适合先找节奏。",
        }),
      ]}
      backupProducts={[]}
      shoppingGuidance={[
        "购买前优先确认是否有明确售后和材质说明。",
        "收到后先完成基础清洁，再进入第一次使用。",
        "第一次开始时先从更低档位与更短时长试起。",
      ]}
      recommendationTips={["如果同住，先优先比较更安静的路线。"]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.match(html, /关键判断/);
  assert.match(html, /外部路线更适合先找身体反馈/);
  assert.doesNotMatch(html, /下单前确认/);
  assert.doesNotMatch(html, /为什么这条路线更适合你/);
  assert.doesNotMatch(html, /这次更适合先走/);
  assert.doesNotMatch(html, /收货后第一步/);
  assert.doesNotMatch(html, /查看下一步建议/);
});

test("female MVP hides the parameter explanation entry near metric chips", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /了解参数怎么看/);
  assert.doesNotMatch(html, /噪音 &lt; 42dB/);
  assert.doesNotMatch(html, /防水 IPX7/);
  assert.doesNotMatch(html, /看静音与场景/);
  assert.doesNotMatch(html, /看清洁与护理/);
  assert.doesNotMatch(html, /看参数原理/);
});

test("female MVP hides metric chips as direct knowledge entry points", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /了解这个参数/);
  assert.doesNotMatch(html, /cursor-pointer/);
  assert.doesNotMatch(html, /噪音 &lt; 42dB/);
  assert.doesNotMatch(html, /防水 IPX7/);
  assert.doesNotMatch(html, /温柔电机/);
});

test("female MVP hides the inline parameter preview layer for chip explanations", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /看懂这次推荐，不用把参数全背下来/);
  assert.doesNotMatch(html, /先看一眼核心判断/);
  assert.doesNotMatch(html, /去知识星云深读/);
});

test("female MVP keeps parameter preview code recoverable but hidden from output", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["静音待判断", "清洁待判断"],
        maxDb: 40,
        waterproof: 7,
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );
  const source = fs.readFileSync(
    path.resolve(process.cwd(), "src/pages/ResultsPage.tsx"),
    "utf8",
  );

  assert.doesNotMatch(html, /静音参数/);
  assert.doesNotMatch(html, /防水边界/);
  assert.doesNotMatch(html, /电机体感/);
  assert.doesNotMatch(source, /ResultsParameterEducationSection/);
  assert.doesNotMatch(source, /getSortedParameterPreviewItems/);
});

test("female MVP hides motor guidance even when the user's current concern is body feedback", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{
        tags: ["敏感度待判断"],
        motorType: "gentle",
        experienceLevel: "sensitive",
      }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /电机体感/);
  assert.doesNotMatch(html, /静音参数/);
});

test("female MVP hides model selection details and regenerate recommendation entry", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
    />,
  );

  assert.doesNotMatch(html, /对当前结果不满意？/);
  assert.doesNotMatch(html, /再给我一版更贴合现在需求的推荐/);
  assert.doesNotMatch(html, /一次轻量反馈/);
  assert.doesNotMatch(html, /想更准一点/);
  assert.doesNotMatch(html, /想换个风格/);
  assert.doesNotMatch(html, /这版没看懂/);
  assert.doesNotMatch(html, /换个模型再试/);
  assert.doesNotMatch(html, /当前模型/);
  assert.doesNotMatch(html, /Mimo（DMX）/);
  assert.doesNotMatch(html, /Qwen（DMX）/);
  assert.doesNotMatch(html, /mimo-v2\.5-free/);
});

test("results page offers separate restart and return-home actions", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
      onBackHome={() => {}}
    />,
  );

  assert.match(html, /重新回答偏好问题/);
  assert.match(html, /返回首页/);
});

test("results page adapts the reset button copy for natural-language matching", () => {
  const html = renderToStaticMarkup(
    <ResultsPage
      pageVariants={{}}
      answers={{ tags: ["静音"] }}
      topProducts={[makeProduct({ id: "p1", name: "Primary Pick" })]}
      backupProducts={[]}
      shoppingGuidance={[]}
      recommendationTips={[]}
      isRecalibratingResults={false}
      onReset={() => {}}
      matchInputMode="natural-language"
      naturalLanguageQuery="想要静音、好清洁的"
    />,
  );

  assert.match(html, /重新输入需求描述/);
  assert.doesNotMatch(html, /重新回答偏好问题/);
});
